### ISSUE TITLE
got an uncaught exception, is there anything goes wrong in your rule file ?

### ISSUE THREAD

**Issue by 0xMorty9** [naah69/wx_dump_change_score#11]
hello@hellodeiMac  ~/Desktop  anyproxy -i --rule wx_dump_change_score-master/wxdump.js
[AnyProxy ERROR][2018-01-04 11:53:51]: got an uncaught exception, is there anything goes wrong in your rule file ?
Error: listen EADDRINUSE :::8002
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at Server.setupListenHandle [as _listen2] (net.js:1344:14)
    at listenInCluster (net.js:1385:12)
    at Server.listen (net.js:1469:7)
    at Function.listen (/usr/local/lib/node_modules/anyproxy/node_modules/express/lib/application.js:618:24)
    at co.then (/usr/local/lib/node_modules/anyproxy/lib/webInterface.js:337:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
[AnyProxy Log][2018-01-04 11:53:51]: clearing cache file...
[AnyProxy Log][2018-01-04 11:53:51]: closing webserver...

配置这里的时候 报错 请问大概是什么原因

**Comment by 0xMorty9** [comment]
我的锅~ 8002端口被占用了

**Comment by naah69** [comment]
哈哈

**Comment by 0xMorty9** [comment]
但是一直刷不成功 哈哈哈哈  所有步骤都没有问题

**Comment by pyang30** [comment]
重启手机试试，分数就变了


| |
杨鹏昊
|
|
邮箱：phil.y@163.com
|

签名由 网易邮箱大师 定制

在2018年01月04日 12:27，520xiaopohai 写道：

但是一直刷不成功 哈哈哈哈 所有步骤都没有问题

**Comment by naah69** [comment]
原来的方法 微信已经封锁了

**Comment by jingce** [comment]
https://github.com/Jingce-lu/wxt1tsf 亲测可以成功

**Comment by naah69** [comment]
这个在V2EX上见到过，应该不是原创了吧，数据固化替换，很容易被封的
